# -*- coding: utf-8 -*-
"""Lista Inicial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KoKnbwB9P1OO1ptsqLhpOr-Gcr-liuqM

Exercício 1
"""

#Mostrar na tela o produto entre 28 e 45
valor= 28*45
print('28 x 45 =')
print(valor)

"""Exercicio 2"""

#Mostrar a média aritmética entre 3 números passados pelo usuário.
num1=int(input("¹Numero: "))
num2=int(input("²Numero: "))
num3=int(input("³Numero: "))
total=num1+num2+num3
mediaarit=total//3
print("A Média Artimética desses 3 números é:")
print(mediaarit)

"""Exercício 3"""

#Leia um número e mostre seu sucessor e seu antecessor na tela.
numero=int(input("Insira o numero:"))
antecessor=numero-1
sucessor=numero+1
print("Antecessor: ")
print(antecessor)
print("Sucessor: ")
print(sucessor)

"""Exercício 4"""

#Leia dois números e mostre a soma. Ante do resultado, deverá aparecer a mensagem conforme abaixo:
num1=int(input("Número A: "))
num2=int(input("Número B: "))
soma=num1+num2
print("A soma de A+B é igual a: ")
print(soma)

"""Exercício 5"""

#Leia um número e mostre a terça parte deste número.
Num=int(input("Insira o número: "))
terca=Num//3
print("a terça parte deste número é: ")
print(terca)

"""Exercício 6"""

#Faça um algoritmo que converta um montante em real para dólar, para tal peça o valor em real que se deseja converter e a cotação atual
mont=float(input("Insira a quantidade de Reais que deseja converter: "))
dolar=float(input("Insira a cotação atual do dólar: "))
va=mont/dolar
print('Resultado: ')
print(va)

"""Exercício 7"""

#A máquina 1 produz 1 poste por dia, a máquina 2 produz 3 e a máquina 3 produz 2,5.  
#Faça um programa que calcule o número de postes produzidos por esta usina para
#uma quantidade de dias informada.
maq123=float(6.5)
print('Produção diára de postes: 6.5')
dias=float(input('Quantidade de dias: '))
valorfinal=maq123*dias
print("A Usina produzirá: ")
print(valorfinal)
print('postes em')
print(dias)
print('dias.')

"""Exercício 8"""

#O professor gostaria de ter um algoritmo para calcular a média da disciplina Algoritmos.
#Ele aplica 3 provas, sendo que a primeira tem peso 3, a segunda peso 2 e a terceira peso 5.
nota1=float(input("Nota prova 1: "))
nota2=float(input("Nota prova 2: "))
nota3=float(input("Nota prova 3: "))
nota1cpeso=nota1*0.3
nota2cpeso=nota2*0.2
nota3cpeso=nota3*0.5
media1=nota1cpeso+nota2cpeso+nota3cpeso
print("A média é: ")
print(media1)